import { BaseProps } from "./AutoComplete.types";

export const mockSuggestions: BaseProps[] = [
  { id: "0,", label: "Alabama" },
  { id: "1,", label: "Alaska" },
  { id: "2,", label: "American Samoa" },
  { id: "3,", label: "Arizona" },
  { id: "4,", label: "Arkansas" },
  { id: "5,", label: "California" },
  { id: "6,", label: "Colorado" },
  { id: "7", label: "Connecticut" },
  { id: "8", label: "Delaware" },
  { id: "9,", label: "District Of Columbia" },
  { id: "10", label: "Federated States Of Micronesia" },
  { id: "11", label: "Florida" },
  { id: "12", label: "Georgia" },
  { id: "13", label: "Guam" },
  { id: "14", label: "Hawaii" },
  { id: "15", label: "Idaho" },
  { id: "16", label: "Illinois" },
  { id: "17", label: "Indiana" },
  { id: "18", label: "Iowa" },
  { id: "19", label: "Kansas" },
  { id: "20", label: "Kentucky" },
  { id: "21", label: "Louisiana" },
  { id: "22", label: "Maine" },
  { id: "23", label: "Marshall Islands" },
  { id: "24", label: "Maryland" },
  { id: "25", label: "Massachusetts" },
  { id: "26", label: "Michigan" },
  { id: "27", label: "Minnesota" },
  { id: "28", label: "Mississippi" },
  { id: "29", label: "Missouri" },
  { id: "30", label: "Montana" },
  { id: "31", label: "Nebraska" },
  { id: "32", label: "Nevada" },
  { id: "33", label: "New Hampshire" },
  { id: "34", label: "New Jersey" },
  { id: "35", label: "New Mexico" },
  { id: "36", label: "New York" },
  { id: "37", label: "North Carolina" },
  { id: "38", label: "North Dakota" },
  { id: "39", label: "Northern Mariana Islands" },
  { id: "40", label: "Ohio" },
  { id: "41", label: "Oklahoma" },
  { id: "42", label: "Oregon" },
  { id: "43", label: "Palau" },
  { id: "44", label: "Pennsylvania" },
  { id: "45", label: "Puerto Rico" },
  { id: "46", label: "Rhode Island" },
  { id: "47", label: "South Carolina" },
  { id: "48", label: "South Dakota" },
  { id: "49", label: "Tennessee" },
  { id: "50", label: "Texas" },
  { id: "51", label: "Utah" },
  { id: "52", label: "Vermont" },
  { id: "53", label: "Virgin Islands" },
  { id: "54", label: "Virginia" },
  { id: "55", label: "Washington" },
  { id: "56", label: "West Virginia" },
  { id: "57", label: "Wisconsin" },
  { id: "58", label: "Wyoming" },
];
